#Page.ObjectName.Locator=value given by developer

# Login Page Objects
Login.UserName.Id=username
Login.Password.Id=password
Login.LoginButton.Class=decorativeSubmit
Login.Error.Id=errorDiv

# Home Page Objects
Home.UserName.Xpath=//div[@id='form']/h2
Home.Logout.Class=decorativeSubmit
Home.CRMSFA.Link=CRM/SFA


# Home Page Objects
MyHome.Leads.Link=Leads

# My Leads Page Objects
MyLeads.CreateLead.Link=Create Lead
MyLeads.FindLeads.Link=Find Leads
MyLeads.MergeLeads.Link=Merge Leads

# Create Lead Page Objects
CreateLead.CompanyName.Id=createLeadForm_companyName
CreateLead.FirstName.Id=createLeadForm_firstName
CreateLead.LastName.Id=createLeadForm_lastName
CreateLead.CreateLead.Name=submitButton

# View Lead Page Objects
ViewLead.FirstName.Id=viewLead_firstName_sp
ViewLead.CompanyName.Id=viewLead_companyName_sp
ViewLead.Edit.Link=Edit
ViewLead.Duplicate.Link=Duplicate Lead
ViewLead.Delete.Link=Delete


# Find Lead Page Objects
FindLead.NameID.Xpath=//span[contains(text(),'Name and ID')]
FindLead.LeadID_NameID.Xpath=//label[text()='Lead ID:']/following::input[@name='id']
FindLead.FirstName_NameID.Xpath=//label[text()='Lead ID:']/following::input[@name='firstName']
FindLead.LastName_NameID.Xpath=//label[text()='Lead ID:']/following::input[@name='lastName']
FindLead.CompanyName_NameID.Xpath=//label[text()='Lead ID:']/following::input[@name='companyName']
FindLead.Phone.Xpath=//span[contains(text(),'Phone')]
FindLead.Phonenumber_Phone.Xpath=//label[text()='Phone Number:']/following::input[@name='phoneNumber']
FindLead.Email.Xpath=//span[contains(text(),'Email')]
FindLead.EmailAddress_Email.Xpath=//label[text()='Email Address:']/following::input[@name='emailAddress']
FindLead.FindLeadButton.Xpath=//button[text()='Find Leads']
FindLead.FirstResultLeadID.Xpath=(//div[@class='x-grid3-cell-inner x-grid3-col-partyId'])[1]/a
FindLead.FirstResultLeadName.Xpath=(//div[@class='x-grid3-cell-inner x-grid3-col-firstName'])[1]/a
FindLead.NoRecordPresent.Xpath=//div[@class='x-paging-info']

# Edit Lead Page Objects
EditLead.CompanyName.Id=updateLeadForm_companyName
EditLead.UpateButton.Xpath=//input[@value='Update']

# Duplicate Lead Page Objects
DuplicateLead.SectionHeaderTitle.Xpath=//div[@class='x-panel-header sectionHeaderTitle']
DuplicateLead.CompanyName.Id=createLeadForm_companyName
DuplicateLead.FirstName.Id=createLeadForm_firstName
DuplicateLead.LastName.Id=createLeadForm_lastName
DuplicateLead.CreateLead.Name=submitButton

# Merge Lead Page Objects
MergeLead.FromLeadIcon.Xpath=(//img[@alt='Lookup'])[1]
MergeLead.ToLeadIcon.Xpath=(//img[@alt='Lookup'])[2]
MergeLead.MergeLeadButton.Link=Merge


